### ISSUE TITLE
No function was found that matched the signature provided

### ISSUE THREAD

**Issue by angelortiz-dev** [CrackerakiUA/ngImgCropFullExtended#180]
Hello guys, I have an error when I try to pass a File object to the img-crop directive, this is my plunker: https://plnkr.co/edit/PYuhtG3A0G3demFKO7Hf?p=preview

The error is:

```
VM5421 angular.min.js:118 TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at TypeError (native)
    at https://cdn.rawgit.com/CrackerakiUA/ngImgCropFullExtended/master/compile/minified/ng-img-crop.js:2:9785
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js:131:20
    at m.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js:145:347)
    at m.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js:142:420)
    at m.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js:146:113)
    at https://cdn.rawgit.com/CrackerakiUA/ngImgCropFullExtended/master/compile/minified/ng-img-crop.js:2:10519
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js:158:494
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js:45:444)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js:48:300
```

I will appreciate any help.

**Comment by angelortiz-dev** [comment]
This happens when I use bindToController or scope definition, in that case the error disappear if I convert the blob into a file in that line:

```
cropHost.getResultImageDataBlob().then(function (blob) {
  scope.resultBlob = blob;
  var file = new File([blob], 'filename', {type: 'contentType', lastModified: Date.now()});
  scope.urlBlob = urlCreator.createObjectURL(file);
});
```

but obviously that needs the correct contentType and filename.

**Comment by rickerd** [comment]
This repo is dead.
Please move to the other project:
https://github.com/CrackerakiUA/ui-cropper
